def use_base_exception():
	raise Exception
	raise Exception("awesome")